# Generated by Django 5.1.2 on 2025-02-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0002_rename_location_junction_city_remove_junction_city_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, unique=True)),
                ("fine_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name="junction",
            old_name="City",
            new_name="city",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="city",
            field=models.CharField(default="Unknown City", max_length=100),
        ),
        migrations.AddField(
            model_name="licenseplatelog",
            name="violation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.violation",
            ),
        ),
    ]
